SukiSU-Ultra/SukiSU-Ultra

docs/README-en.md
docs/README-ja.md
docs/README-tr.md
docs/README.md
manager/app/src/main/AndroidManifest.xml
manager/app/src/main/java/com/sukisu/ultra/ui/screen/MoreSettings.kt
manager/app/src/main/res/drawable/ic_launcher_foreground_alt.xml
manager/app/src/main/res/drawable/ic_launcher_monochrome_alt.xml
manager/app/src/main/res/mipmap-anydpi-v26/ic_launcher_alt.xml
manager/app/src/main/res/mipmap-anydpi-v26/ic_launcher_alt_round.xml
manager/app/src/main/res/values-zh-rCN/strings.xml
manager/app/src/main/res/values-zh-rHK/strings.xml
manager/app/src/main/res/values-zh-rTW/strings.xml
manager/app/src/main/res/values/strings.xml

- add alternate launcher icon resources
- create activity alias for alternate icon
- add setting to toggle app icon in more settings screen
- move icon toggle into custom settings section
- translate icon toggle strings into Chinese

manager: Add alternate app icon toggle

---

manager/app/src/main/java/com/sukisu/ultra/ui/screen/Home.kt
manager/app/src/main/java/com/sukisu/ultra/ui/screen/MoreSettings.kt
manager/app/src/main/java/com/sukisu/ultra/ui/screen/Settings.kt
manager/app/src/main/java/com/sukisu/ultra/ui/theme/CardManage.kt
manager/app/src/main/java/com/sukisu/ultra/ui/theme/Theme.kt

prepare for Material 3
1. cancel shadow
2. a11y optimized in setting
3. activation card color use the color palette more accurately

manager: style optizmized

---

kernel/core_hook.c

`ksu handles devpts with selinux lsm hook` - aviraxp
- no, not yet, but yes we can, thats a good idea.
This change tries to do that, so instead of hooking pts_unix98_lookup or
devpts_get_priv, we just watch security_inode_permission, if its devpts,
pass it along to the original handler.
Signed-off-by: backslashxx <118538522+backslashxx@users.noreply.github.com>

kernel: core_hook: intercept devpts via security_inode_permission LSM

---

docs/README-en.md
docs/README.md

#114 #67 cannot boot given GKI build on Pixel. It seem like ZRAM patches cannot work okey on Pixel devices.
Therefore provide a less change build.

Add myself GKI build in README for Pixel users

---

kernel/Kconfig

make sure kpm config requirement was enabled for non-gki

kernel: select KALLSYMS & KALLSYMS_ALL

---

kernel/Kconfig
kernel/core_hook.c

Add select for KPM: #224 (cherry pick)

Kernel: Revert fix & Add select for KPM

---

kernel/Kconfig

kernel: fix Missing `endmenu`

---

manager/app/src/main/java/com/sukisu/ultra/ui/screen/SuSFSConfig.kt

只在ab分区设备上在susfs设置里显示槽位信息
（还是有人在用 A-Only 分区设备的
PS：没学过Kotlin，写的不好，但至少实现了（）

manager: Only display slotinformation on AB devices

---

manager/app/src/main/java/com/sukisu/ultra/ui/viewmodel/HomeViewModel.kt

修复由于不当的协程异常捕获导致的manager升级崩溃

---

docs/README-en.md
docs/README-ja.md
docs/README-tr.md
docs/README.md

After being reminded by 明风OuO, the emoji package was not drawn as 五十根大虾仁 but as 怡子曰曰. Therefore, it was changed.

copyright: Correct copyright owner information

---

manager/app/src/main/res/values/strings.xml

manager: fix typo in hide_zygisk_implement string and summary

---

manager/app/build.gradle.kts
manager/app/proguard-rules.pro
manager/app/src/main/java/com/sukisu/ultra/KernelSUApplication.kt
manager/app/src/main/java/com/sukisu/ultra/ui/screen/Module.kt
manager/app/src/main/java/com/sukisu/ultra/ui/theme/Theme.kt
manager/app/src/main/java/com/sukisu/ultra/ui/util/SuSFSManager.kt
manager/app/src/main/java/com/sukisu/ultra/ui/viewmodel/HomeViewModel.kt
manager/app/src/main/java/com/sukisu/ultra/ui/webui/KsuLibSuProvider.kt
manager/app/src/main/java/com/sukisu/ultra/ui/webui/SuService.kt
manager/app/src/main/java/com/sukisu/ultra/ui/webui/WebUIActivity.kt
manager/app/src/main/java/com/sukisu/ultra/ui/webui/WebUIXActivity.kt
manager/app/src/main/java/com/sukisu/ultra/ui/webui/WebViewInterface.kt
manager/gradle/libs.versions.toml

- Updated to the latest version of WebUI X Portable
- Plugins are disabled for security reasons and to make the APK not unnecessary big.
- Updated MMRL libraries to the latest version

manager: Update WebUI X to the latest version

---

manager/app/src/main/res/values-ja/strings.xml

When Japanese translations are updated from Crowdin, they are preferentially rolled back on the repository side, so creating a Pull Request.

Fix Japanese

---

kernel/kpm/kpm.c

kpm: fix compilation errors

---

userspace/ksud/Cargo.lock
userspace/ksud/Cargo.toml

using
```toml
[profile.release]
overflow-checks = false
codegen-units = 1
lto = "fat"
opt-level = 3
strip = true
```
to optimize ksud compilation products

feat: Optimize ksud compilation products

---

kernel/core_hook.c
kernel/kernel_compat.c
kernel/kernel_compat.h
kernel/ksud.c
kernel/ksud.h

make sure to test everything.
kprobes_hook=n, kprobes_hook=y and LKM.

ksud: migrate ksud execution to security_bprm_check

---

kernel/kpm/kpm.c

kpm: remove incorrect "<" to fix compilation error

---

kernel/core_hook.c

Commit:
https://gitlab.com/simonpunk/susfs4ksu/-/commit/8e8150bf1e9a7eb5648eccf25dfe0af6cfc3c095 https://gitlab.com/simonpunk/susfs4ksu/-/commit/de64f31024bbbf4aaad64be3fc6d0cd0417edf60 https://gitlab.com/simonpunk/susfs4ksu/-/commit/0e19a05277d28182c7b653580117145c53e69e92
Co-authored-by: JackAltman
<82563979+JackA1ltman@users.noreply.github.com>

susfs: merged latest commit.

---

kernel/selinux/sepolicy.c

Fix issue in Kirin 970 HarmonyOS2 kernel
Error:
In the Kirin 970 HarmonyOS2 kernel source, integrating SukiSU requires disabling `CONFIG_HKIP_SELINUX_PROT`, which enables flex_array. However, in **kernel/selinux/sepolicy.c**, the functions `add_type` and `add_typeattribute_raw` still use ebitmap instead of flex_array when a Huawei HISI device is detected, causing errors.
Fix:
Added conditional checks in add_type and add_typeattribute_raw. An EMUI10-only kernel configuration option is used to distinguish source code versions, since the EMUI10 kernel does not use flex_array.

kernel: Fix huawei kernel bug

---

kernel/ksu.c

Fiz issue https://github.com/SukiSU-Ultra/SukiSU-Ultra/issues/364
https://github.com/torvalds/linux/commit/cdd30ebb1b9f36159d66f088b61aee264e649d7a

Add support for 6.13
